version: '3.9'

services:

  postgres:
    image: postgres:16

    container_name: rca-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: rca
      POSTGRES_PASSWORD: rca1234
      POSTGRES_DB: rcadb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rca -d rcadb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

