"""initial schema

Revision ID: e024883288db
Revises: 
Create Date: 2026-08-27 18:33:22.711553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e024883288db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('alert_ids', sa.JSON(), nullable=False),
    sa.Column('suspected_cause', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_index(op.f('ix_alert_groups_id'), 'alert_groups', ['id'], unique=False)
    op.create_index(op.f('ix_alert_groups_window_id'), 'alert_groups', ['window_id'], unique=False)
    op.create_table('alert_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_windows_id'), 'alert_windows', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_name', sa.String(), nullable=False),
    sa.Column('instance', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('rca_status', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_alert_id'), 'evidence', ['alert_id'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_table('rca_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=False),
    sa.Column('root_cause_detail', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('affected_hosts', sa.JSON(), nullable=True),
    sa.Column('alert_types', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_findings_group_id'), 'rca_findings', ['group_id'], unique=False)
    op.create_index(op.f('ix_rca_findings_id'), 'rca_findings', ['id'], unique=False)
    op.create_index(op.f('ix_rca_findings_window_id'), 'rca_findings', ['window_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rca_findings_window_id'), table_name='rca_findings')
    op.drop_index(op.f('ix_rca_findings_id'), table_name='rca_findings')
    op.drop_index(op.f('ix_rca_findings_group_id'), table_name='rca_findings')
    op.drop_table('rca_findings')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_alert_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_windows_id'), table_name='alert_windows')
    op.drop_table('alert_windows')
    op.drop_index(op.f('ix_alert_groups_window_id'), table_name='alert_groups')
    op.drop_index(op.f('ix_alert_groups_id'), table_name='alert_groups')
    op.drop_table('alert_groups')
    # ### end Alembic commands ###
